namespace Pixa.Soundbridge
{
    public enum IRCommand
    {
        [IRCommandString("CK_NORTH")]
        North,
        [IRCommandString("CK_SOUTH")]
        South,
        [IRCommandString("CK_WEST")]
        West,
        [IRCommandString("CK_EAST")]
        East,
        [IRCommandString("CK_PLAY")]
        Play,
        [IRCommandString("CK_PAUSE")]
        Pause,
        [IRCommandString("CK_PLAYPAUSE")]
        PlayPause,
        [IRCommandString("CK_STOP")]
        Stop,
        [IRCommandString("CK_NEXT")]
        Next,
        [IRCommandString("CK_PREVIOUS")]
        Previous,
        [IRCommandString("CK_MENU")]
        Menu,
        [IRCommandString("CK_INFO")]
        Info,
        [IRCommandString("CK_EXIT")]
        Exit,
        [IRCommandString("CK_POWER")]
        Power,
        [IRCommandString("CK_POWER_ON")]
        PowerOn,
        [IRCommandString("CK_POWER_OFF")]
        PowerOff,
        [IRCommandString("CK_SEARCH")]
        Search,
        [IRCommandString("CK_ADD")]
        Add,
        [IRCommandString("CK_REPEAT")]
        Repeat,
        [IRCommandString("CK_VOLUME_UP")]
        VolumeUp,
        [IRCommandString("CK_VOLUME_DOWN")]
        VolumeDown,
        [IRCommandString("CK_BRIGHTNESS")]
        Brightness,
        [IRCommandString("CK_ROTARY_CLOCKWISE")]
        RotaryClockwise,
        [IRCommandString("CK_ROTARY_COUNTERCLOCKWISE")]
        RotaryCounterClockwise,
        [IRCommandString("CK_ROTARY_SWITCH")]
        RotarySwitch,
        [IRCommandString("CK_SNOOZE")]
        Snooze,
        [IRCommandString("CK_SOURCE")]
        Source,
        [IRCommandString("CK_SCAN_UP")]
        ScanUp,
        [IRCommandString("CK_SCAN_DOWN")]
        ScanDown,
        [IRCommandString("CK_GROUP")]
        Group,
        [IRCommandString("CK_ALARM")]
        Alarm,
        [IRCommandString("CK_PLAYLISTS")]
        Playlists,
        [IRCommandString("CK_BROWSE_ARTISTS")]
        BrowseArtists,
        [IRCommandString("CK_BROWSE_ALBUMS")]
        BrowseAlbums,
        [IRCommandString("CK_BROWSE_SONGS")]
        BrowseSongs,
        [IRCommandString("CK_BROWSE_GENRES")]
        BrowseGenres,
        [IRCommandString("CK_BROWSE_COMPOSERS")]
        BrowseComposers,
        [IRCommandString("CK_PRESET_A1")]
        PresetA1,
        [IRCommandString("CK_PRESET_A2")]
        PresetA2,
        [IRCommandString("CK_PRESET_A3")]
        PresetA3,
        [IRCommandString("CK_PRESET_A4")]
        PresetA4,
        [IRCommandString("CK_PRESET_A5")]
        PresetA5,
        [IRCommandString("CK_PRESET_A1")]
        PresetA6,
        [IRCommandString("CK_PRESET_B1")]
        PresetB1,
        [IRCommandString("CK_PRESET_B2")]
        PresetB2,
        [IRCommandString("CK_PRESET_B3")]
        PresetB3,
        [IRCommandString("CK_PRESET_B4")]
        PresetB4,
        [IRCommandString("CK_PRESET_B5")]
        PresetB5,
        [IRCommandString("CK_PRESET_B6")]
        PresetB6,
        [IRCommandString("CK_PRESET_C1")]
        PresetC1,
        [IRCommandString("CK_PRESET_C2")]
        PresetC2,
        [IRCommandString("CK_PRESET_C3")]
        PresetC3,
        [IRCommandString("CK_PRESET_C4")]
        PresetC4,
        [IRCommandString("CK_PRESET_C5")]
        PresetC5,
        [IRCommandString("CK_PRESET_C6")]
        PresetC6,
        [IRCommandString("CK_INTERNET_RADIO")]
        InternetRadio,
        [IRCommandString("CK_FM_RADIO")]
        FmRadio,
        [IRCommandString("CK_AM_RADIO")]
        AmRadio,
        [IRCommandString("CK_LAST_MUSIC_SERVER")]
        LastMusicServer,
        [IRCommandString("CK_VOLUME_50")]
        Volume50
    }
}